/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author shehr
 */
public final class Chef_menu extends javax.swing.JFrame {

    /**
     * Creates new form Chef_menu
     */
    public Chef_menu() {
        initComponents();
        fillTable();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public Connection OracleConnection() {
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "shehreen", "oliveoil1000");
//            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:morcl", "shehreen", "oliveoil1000");
            return conn;
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "oracle Connection Failed...");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfield_id = new javax.swing.JTextField();
        textfield_name = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        textfield_amount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        chef_interface = new javax.swing.JButton();
        textfield_name1 = new javax.swing.JTextField();
        textfield_search1 = new javax.swing.JTextField();
        textfield_amount1 = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textfield_id1 = new javax.swing.JTextField();

        textfield_id.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N

        textfield_name.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N

        textfield_amount.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(getMaximumSize());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chef Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        update.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        update.setText("Add");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 240, 174, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price (BDT)", "Available Servings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 1373, 200));

        chef_interface.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        chef_interface.setText("Back to Chef Interface");
        chef_interface.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chef_interfaceMouseClicked(evt);
            }
        });
        jPanel1.add(chef_interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 800, -1, -1));

        textfield_name1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel1.add(textfield_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 790, -1));

        textfield_search1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        textfield_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield_search1KeyReleased(evt);
            }
        });
        jPanel1.add(textfield_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 608, -1));

        textfield_amount1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel1.add(textfield_amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 790, -1));

        clear.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 310, 174, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new bg.jpg"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(2055, 1138));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        textfield_id1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel1.add(textfield_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 196, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showItemToFields(int index) {
        textfield_id1.setText(Integer.toString(retrieveData().get(index).getId()));
        textfield_name1.setText(retrieveData().get(index).getName());
    }

    public ArrayList<MenuBean> retrieveData() {
        ArrayList<MenuBean> al = new ArrayList<MenuBean>();

        try {
            Connection conn = OracleConnection();
            String qry = "select * from menu";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qry);

            while (rs.next()) {
                MenuBean menu = new MenuBean(rs.getInt(1), rs.getString("name"), rs.getInt(3), rs.getInt(4));
                al.add(menu);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        return al;
    }

    public void fillTable() {
        ArrayList<MenuBean> al = null;
        al = retrieveData();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Empty/clear the table

        for (MenuBean menu : al) {
            Object row[] = {menu.getId(), menu.getName(), menu.getPrice(), menu.getAmount()};
            model.addRow(row);
        }
    }


    private void chef_interfaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chef_interfaceMouseClicked
        // TODO add your handling code here:
        Chef_interface ci = new Chef_interface();
        ci.setVisible(true);
        dispose();
    }//GEN-LAST:event_chef_interfaceMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ind = jTable1.getSelectedRow();
        showItemToFields(ind);
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (textfield_id.getText() != null || textfield_name != null || textfield_amount != null) {
            String qry;
            PreparedStatement ps;
            Connection conn = OracleConnection();
            try {
                qry = "update menu set Amount=Amount+? where id=?";
                ps = conn.prepareStatement(qry);

                ps.setInt(1, Integer.parseInt(textfield_amount1.getText()));
                ps.setString(2, textfield_name1.getText());
                ps.setInt(2, Integer.parseInt(textfield_id1.getText()));

                int res = ps.executeUpdate();
                fillTable();
                if (res >= 1) {
                    //JOptionPane.showMessageDialog(null, "Items"+ " have been added.....");
                } else {
                    JOptionPane.showMessageDialog(null, "Item Insertion Failed ....");
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            textfield_id.setText("");
            textfield_name.setText("");
            textfield_amount.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory.......");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        textfield_id1.setText("");
        textfield_name1.setText("");
        textfield_amount1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void textfield_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_search1KeyReleased
        ArrayList<MenuBean> al = null;
        al = new ArrayList<>();
        String val = textfield_search1.getText();
        try {
            Connection conn = OracleConnection();

            String qry = "select * from menu where name like '%" + val + "%'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qry);
            MenuBean menu;
            while (rs.next()) {
                menu = new MenuBean(rs.getInt(1), rs.getString("name"), rs.getInt(3), rs.getInt(4));
                al.add(menu);
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Empty/clear the table
            Object[] row = new Object[4];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getId();
                row[1] = al.get(i).getName();
                row[2] = al.get(i).getPrice();
                row[3] = al.get(i).getAmount();
                model.addRow(row);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_textfield_search1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chef_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chef_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chef_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chef_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chef_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chef_interface;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField textfield_amount;
    private javax.swing.JTextField textfield_amount1;
    private javax.swing.JTextField textfield_id;
    private javax.swing.JTextField textfield_id1;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_name1;
    private javax.swing.JTextField textfield_search1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
