/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author shehr
 */
public final class Manager_Menu extends javax.swing.JFrame {

    /**
     * Creates new form manager_menu
     */
    CallableStatement callstate;
    public Manager_Menu() {
        initComponents();
        fillTable();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public Connection OracleConnection() {
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "shehreen", "oliveoil1000");
//            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:morcl", "shehreen", "oliveoil1000");
            return conn;
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "oracle Connection Failed...");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textfield_price = new javax.swing.JTextField();
        textfield_amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textfield_search = new javax.swing.JTextField();
        managerInterface = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        insert_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textfield_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(2055, 1138));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price (BDT)", "Available Servings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 1200, 187));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manager Menu");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name         : ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 211, -1));

        textfield_name.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel2.add(textfield_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 608, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price           : ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        textfield_price.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        textfield_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_priceActionPerformed(evt);
            }
        });
        jPanel2.add(textfield_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 608, -1));

        textfield_amount.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel2.add(textfield_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 608, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount       :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 211, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Search Item    :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        textfield_search.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        textfield_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_searchActionPerformed(evt);
            }
        });
        textfield_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield_searchKeyReleased(evt);
            }
        });
        jPanel2.add(textfield_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 608, -1));

        managerInterface.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        managerInterface.setText("Back to Manager Interface");
        managerInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerInterfaceActionPerformed(evt);
            }
        });
        jPanel2.add(managerInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 810, -1, -1));

        delete_button.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 390, 295, -1));

        update_button.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 320, 295, -1));

        insert_button.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        insert_button.setText("Insert");
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(insert_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 295, -1));

        clear_button.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 180, 295, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        textfield_id.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel2.add(textfield_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 610, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ind = jTable1.getSelectedRow();
        showItemToFields(ind);
    }//GEN-LAST:event_jTable1MouseClicked

    private void textfield_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_priceActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        textfield_id.setText("");
        textfield_name.setText("");
        textfield_price.setText("");
        textfield_amount.setText("");
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        if (textfield_name != null || textfield_price != null || textfield_amount != null) {
            try {
                Connection conn = OracleConnection();

                PreparedStatement ps = conn.prepareStatement("insert into menu" + "(Name,Price,Amount) values (?,?,?)");
                ps.setString(1, textfield_name.getText());
                ps.setInt(2, Integer.parseInt(textfield_price.getText()));
                ps.setInt(3, Integer.parseInt(textfield_amount.getText()));

                int res = ps.executeUpdate();
                fillTable();

                if (res >= 1) {
                    //JOptionPane.showMessageDialog(null, res+" Number of items"+ " inserted into database .....");
                } else {
                    JOptionPane.showMessageDialog(null, "Item Insertion Failed ....");
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            textfield_name.setText("");
            textfield_price.setText("");
            textfield_amount.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "All fields are compulsory ....");
        }
    }//GEN-LAST:event_insert_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        if (textfield_name != null || textfield_price != null || textfield_amount != null) {
            Connection conn = OracleConnection();
            try {
                callstate = conn.prepareCall("{call updateManagerMenu(?,?,?)}");
                callstate.registerOutParameter(3, Types.VARCHAR);

                int newPrice = Integer.parseInt(textfield_price.getText());
                int newId = Integer.parseInt(textfield_id.getText());

                callstate.setInt(1,newId);
                callstate.setInt(2,newPrice);

                callstate.execute();
                fillTable();

                String finalResult= callstate.getString(3).toString();
                JOptionPane.showMessageDialog(null, finalResult);
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            textfield_name.setText("");
            textfield_price.setText("");
            textfield_amount.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory.......");
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
           
        try {
            Connection conn = OracleConnection();
            callstate = conn.prepareCall("{call deleteMenu(?)}");               
            int newId = Integer.parseInt(textfield_id.getText());
            callstate.setInt(1,newId);
            callstate.execute();
            fillTable();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        textfield_id.setText("");
        textfield_name.setText("");
        textfield_amount.setText("");
        textfield_price.setText("");
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void managerInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerInterfaceActionPerformed
        dispose();
        new Manager_interface().setVisible(true);
    }//GEN-LAST:event_managerInterfaceActionPerformed

    private void textfield_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_searchActionPerformed

    private void textfield_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_searchKeyReleased
        ArrayList<MenuBean> al = null;
        al = new ArrayList<>();
        String val = textfield_search.getText();
        try {
            Connection conn = OracleConnection();

            String qry = "select * from menu where name like '%" + val + "%'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qry);
            MenuBean menu;
            while (rs.next()) {
                menu = new MenuBean(rs.getInt(1), rs.getString("name"), rs.getInt(3), rs.getInt(4));
                al.add(menu);
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Empty/clear the table
            Object[] row = new Object[4];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getId();
                row[1] = al.get(i).getName();
                row[2] = al.get(i).getPrice();
                row[3] = al.get(i).getAmount();
                model.addRow(row);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_textfield_searchKeyReleased

    public void showItemToFields(int index) {
        textfield_id.setText(Integer.toString(retrieveData().get(index).getId()));
        textfield_name.setText(retrieveData().get(index).getName());
        textfield_price.setText(Integer.toString(retrieveData().get(index).getPrice()));
        textfield_amount.setText(Integer.toString(retrieveData().get(index).getAmount()));
    }

    public ArrayList<MenuBean> retrieveData() {
        ArrayList<MenuBean> al = new ArrayList<>();

        try {
            Connection conn = OracleConnection();
            String qry = "select * from menu";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qry);
            MenuBean menu;
            while (rs.next()) {
                menu = new MenuBean(rs.getInt(1), rs.getString("name"), rs.getInt(3), rs.getInt(4));
                al.add(menu);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        return al;
    }

    public void fillTable() {
        ArrayList<MenuBean> al = retrieveData();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (MenuBean menu : al) {
            Object row[] = {menu.getId(), menu.getName(), menu.getPrice(), menu.getAmount()};
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton managerInterface;
    private javax.swing.JTextField textfield_amount;
    private javax.swing.JTextField textfield_id;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_price;
    private javax.swing.JTextField textfield_search;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
